#!/bin/bash

####TODO####
#verificar se img existe

####Váriáveis####
IMG=/work/img/$2
BRANCO=/work/img/branco.png
PRETO=/work/img/preto.png
PANIC=/work/img/panic.png
####Váriáveis####


####Funções####

function f_instala() 
{
	apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean && apt-get clean
	apt-get install fbi git -y
	mkdir -p /work/img /work/temp
	chmod -R 777 /work	
	chmod -R 777 /etc/scripts	
	cd /work/temp
	git clone https://github.com/atedim/tela.git
	cd tela/img480
	mv * /work/img
	cd /work
	rm -rf /work/temp
	cd /etc/scripts
	DATA=`date +%d%m%Y` 
	mv tela $DATA.tela.old
	chmod u-x *.old
	curl https://raw.githubusercontent.com/atedim/tela/main/tela -o tela
	chmod u+x tela
	echo fbi -T 2 -d /dev/fb1 -noverbose -a /work/img/hal9000.png  >> ~/.bashrc
}


function f_atualiza() 
{
	apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean && apt-get clean
	rm -rf /work/img /work/temp
	mkdir -p /work/img /work/temp
	chmod -R 777 /work	
	chmod -R 777 /etc/scripts	
	cd /work/temp
	git clone https://github.com/atedim/tela.git
	cd tela/img480
	mv * /work/img
	cd /work
	rm -rf /work/temp
	cd /etc/scripts
	DATA=`date +%d%m%Y` 
	mv tela $DATA.tela.old
	chmod u-x *.old
	curl https://raw.githubusercontent.com/atedim/tela/main/tela -o tela
	chmod u+x tela
}


function f_exibe() 
{
	fbi -T 2 -d /dev/fb1 -noverbose -a $IMG
}


function f_limpa() 
{
	fbi -T 2 -d /dev/fb1 -noverbose -a $BRANCO

}


function f_panic() 
{
	fbi -T 2 -d /dev/fb1 -noverbose -a $PANIC

}


####Funções####

case $1 in 
	
	exibe)
		f_exibe 
	;;

	limpa)
		f_limpa
	;;

	panic)
		f_panic
	;;

		
	*)
		clear
		echo 
		echo Mostra Imagem ver 0.02 18082021
		echo 
		echo 
		echo  exibe = Mostra a imagem informada como parametro
		echo     ex: tela exibe 1.png
		echo 
		echo  limpa = Define imagem como TODO Branco
		echo 
		echo  panic = Define imagem de erro
		echo
		exit 1

esac
